### PR TITLE
Feat reweight

### PR DESCRIPTION
**Pull request by jtwhite79**
A few bug fixes, an pre-alpha implementation of "mean iterations" with ies, where only the mean is updated and the prior ensemble is mean-shifted, which maintains prior (co)variance.

### CODE REVIEW

**Comment by wkitlasten** [comment]
Shifty mean thing!

**Comment by cnicol-gwlogic** [comment]
This looks interesting - thanks. A couple of queries:

1. Do you think this would achieve similar to manually resampling the prior from the ensemble mean or base relisation after say one or two "normal" IES iterations, and then hitting go again? I guess that's a bit like case [C] in your figure 9.3 (?). I have been doing this a little in recent times, as it seems to get my ensemble into a better final place than defining a prior based on field test data / conceptual stuff / etc, and running ies for say 3 iters - the ensemble often seems to get stuck beyond a certain level of fitting in that 3 normal iters case, except in the rare case that my prior happens to be very nicely centered around my obs (which is really just luck, in my view, or the result of manual tweaking pre-PEST). I justify this to myself in that I don't really know what the prior is anyway - we can only take a stab at it.
2. I wonder if this means one might be more likely to get away with smaller ensemble sizes.

Anyway, thanks for the work on this - I'll test it out for sure.

**Comment by jtwhite79** [comment]
@cnicol-gwlogic your points are more or less the reasons for adding this concept.  @edesousa-intera gave me the idea for this, but sounds like others have already been doing it!  

The difference here (compared to running for a two iterations and the updating offline and restarting) is that the mean shifting happens after the subset evaluation but before the full ensemble is run.  So you only loose`ies_subset_size` runs, but it also means you are banking on the subset being a good representation for the relative phi performance of the upgrade.  trade-offs everywhere

Given that spurious correlation is mostly a posterior second-moment/variance issue, these mean-only iterations could be a way to sneak thru with a smaller ensemble...at least in theory.

**Comment by cnicol-gwlogic** [comment]
Thanks @jtwhite79, makes sense. One more I just thought of sorry - I guess we should we turn off "center on base" when using this?

**Comment by jtwhite79** [comment]
That is a good question and and I think you are right that you should probably center on the mean for these operations.  But if the base and mean are close (which they usually are if the base was used as a the prior mean vector), then it might not make too much difference...

**Pull request merged**
