### PR TITLE
Feat cleanup

### PR DESCRIPTION
**Pull request by jwhite-usgs**
renamed ies "base" obs ensemble "obs+noise" ensemble, removed inschekpp

### CODE REVIEW

**Comment by mnfienen-usgs** [comment]
why the rename? just wrote a bunch of `pyemu` code that looks for `base`

**Comment by jtwhite79** [comment]
It’s poor naming on my part but now that the “base” realization is getting more attention (like “base” par and rei files), I feel like it’s going to lead to significant confusion.  So this just means the one ensemble that is the obs vals with additive noise has a different filename,  all the “base” realization stuff remains.

**Comment by mnfienen-usgs** [comment]
Ha! roger that. I suffered from the exact confusion you are fixing :)

**Comment by mwtoews** [comment]
also remove inschekpp referenced from src/utilities/CMakeLists.txt

**Pull request merged**
