### PR TITLE
Add CPack, and modify a few CMake things

### PR DESCRIPTION
**Pull request by mwtoews**
Add more to #45
* Use CPack to bundle executables rather than CMAKE_INSTALL_PREFIX - this will create files like `pestpp-4.3.11-linux.tar.gz`, `pestpp-4.3.11-win.zip`, etc. that can be archived.
* Expand docs on parallel builds for Windows
* Guard against in-source builds and building from src
* Move a few definitions for Windows

Also, AppVeyor will produce .zip files (called artifices) that can be downloaded.

### CODE REVIEW

**Comment by jtwhite79** [comment]
@mwtoews - I tried to run `cmake -G"Visual Studio 16 2019" -A Win64 ..` in an empty `build` dir at the same dir level as `src` and got the following error (this command was working with the last pull request).  Am I doing something wrong?

-- Configuring CMake 3.17.1 to build PESTPP 4.3.11
CMake Error at CMakeLists.txt:16 (project):
  Failed to run MSBuild command:

    C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/MSBuild/Current/Bin/MSBuild.exe

  to get the value of VCTargetsPath:

    Microsoft (R) Build Engine version 16.2.37902+b5aaefc9f for .NET Framework
    Copyright (C) Microsoft Corporation. All rights reserved.

    Build started 4/19/2020 10:26:37 AM.
    Project "C:\Dev\pestpp_usgs\build\CMakeFiles\3.17.1\VCTargetsPath.vcxproj" on node 1 (default targets).
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(775,5): error : The OutputPath property is not set for project 'VCTargetsPath.vcxproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='Win64'.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project. [C:\Dev\pestpp_usgs\build\CMakeFiles\3.17.1\VCTargetsPath.vcxproj]
    Done Building Project "C:\Dev\pestpp_usgs\build\CMakeFiles\3.17.1\VCTargetsPath.vcxproj" (default targets) -- FAILED.

    Build FAILED.

    "C:\Dev\pestpp_usgs\build\CMakeFiles\3.17.1\VCTargetsPath.vcxproj" (default target) (1) ->
    (_CheckForInvalidConfigurationAndPlatform target) ->
      C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(775,5): error : The OutputPath property is not set for project 'VCTargetsPath.vcxproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='Win64'.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project. [C:\Dev\pestpp_usgs\build\CMakeFiles\3.17.1\VCTargetsPath.vcxproj]

        0 Warning(s)
        1 Error(s)

    Time Elapsed 00:00:00.09


  Exit code: 1



-- Configuring incomplete, errors occurred!
See also "C:/Dev/pestpp_usgs/build/CMakeFiles/CMakeOutput.log".

**Comment by mwtoews** [comment]
Good catch. It's a documentation bug, which should have been `-A x64`. (The awkward things that I've encountered is that often 32-bit VS is still default, and 64-bit modes are enabled differently for VS2017 or VS2019). You may need to delete/recreate the build dir before re-running the configure:

    cmake -G"Visual Studio 16 2019" -A x64 ..
    cmake --build . --config Release -j
    cpack -G ZIP

**Comment by mwtoews** [comment]
Oh wait, I just discovered from [the docs](https://cmake.org/cmake/help/latest/generator/Visual%20Studio%2016%202019.html) that the default platform is the same as the host, so you may not need `-A x64` on a x64 host. It's harmless to specify anyways.

**Comment by jtwhite79** [comment]
@mwtoews - working pretty well.  One thing I can't get past is this error on macos:
[100%] Installing local binaries to /Users/jwhite/Dev/pestpp/bin
-- Install configuration: "Release"
-- Installing: /Users/jwhite/Dev/pestpp/bin/pestpp-sen
-- Installing: /Users/jwhite/Dev/pestpp/bin/pestpp-glm
-- Installing: /Users/jwhite/Dev/pestpp/bin/pestpp-ies
-- Installing: /Users/jwhite/Dev/pestpp/bin/pestpp-opt
-- Installing: /Users/jwhite/Dev/pestpp/bin/pestpp-swp
[100%] Built target local_install
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/bin/pestpp-sen
CMake Error at src/programs/gsa/cmake_install.cmake:36 (file):
  file INSTALL cannot copy file
  "/Users/jwhite/Dev/pestpp/build/src/programs/gsa/pestpp-sen" to
  "/usr/local/bin/pestpp-sen": Permission denied.
Call Stack (most recent call first):
  src/programs/cmake_install.cmake:37 (include)
  src/cmake_install.cmake:38 (include)
  cmake_install.cmake:37 (include)

We end up with the new binaries in `./bin/mac` but then there is an extra step of trying a system-level install to `usr/local/bin`.  I chased it down to the `cmake_install.cmake` - there is a conditional on line 35 checking for `CMAKE_INSTALL_LOCAL_ONLY` that seems to not be getting set for the macos build.  Both win and linux dont have this issue. I havent been able to find where this flag is being set.   Here are the commands Im using:

```rm -r build
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=icpc ..
make -j 5 
cpack
```

**Comment by mwtoews** [comment]
This is a new one to me, and I don't have access to a mac to investigate. Does the install attempt happen after the `make` command? I would normally expect this to happen with `make install`. The cmake_install.cmake files are automatically generated.

**Comment by jtwhite79** [comment]
It’s during the make command

**Pull request merged**
